### ISSUE TITLE
prcEditor doesn't open

### ISSUE THREAD

**Issue by MegAmi24** [BenHall-7/paracobNET#12]
It just won't start up. I've tried running as an administrator with no luck. I have NET Core Runtime 3.0 installed so I don't know else could be the problem.

**Comment by BenHall-7** [comment]
I missed this notification, my apologies! Have you made sure to also use the .NET Core Desktop Installer?

For the record I see you opened an older version in the modding Discord, but I recommend a more recent version because of various improvements. If you no longer need help just let me know so I can decide whether the issue needs to be closed

**Comment by MegAmi24** [comment]
I'm using an older version because it's the latest version that won't start up for me.
