### ISSUE TITLE
How Can I Open ParamXML on Mac?

### ISSUE THREAD

**Issue by progenitor7** [BenHall-7/paracobNET#18]
This gamebanana tutorial explains that PRC editor is Windows specific but that ParamXML is cross platform: https://gamebanana.com/tools/6620

I assumed that means both Mac and Linux as well. Am I expected to use Wine or Winebottler on Mac to open the .exe or is there a way for me to open it natively from the terminal?

**Comment by BenHall-7** [comment]
Yeah, prcEditor is windows specific because the WPF library it uses for the UI, Microsoft never intended to support on other platforms. However, .NET Core 3.0 and above are supported on mac and linux systems, so if you install that you will be able to run ParamXML.

From the sound of it, you might be looking for a real GUI app on mac? ParamXML is a terminal/console app so it's only meant to take commands. If that's what you want, you still probably don't need to install .NET, because there is a really good alternative to ParamXML: my rewrite named similarly, `param-xml`, which you can find info about [here](https://github.com/ultimate-research/prc-rs)

There might be some tutorial about using it available in the modding discord, if you are in there. Alternatively, if you need any help with that I can answer questions about them here.

**Comment by progenitor7** [comment]
Sorry for the delay. I ended up getting it to work on bootcamp which makes Smash modding a lot more convenient in general. Thanks a lot for your input! I'll give it a try it again on MacOS if the need arises.
